export const actionType = {
  /*..Login....*/
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  /*..Register ITer....*/
  REGISTER_ITER: 'REGISTER_ITER',
  REGISTER_ITER_FAIL: 'REGISTER_ITER_FAIL',
  REGISTER_ITER_SUCCESS: 'REGISTER_ITER_SUCCESS',
  /*..Register Company....*/
  REGISTER_COMPANY: 'REGISTER_COMPANY',
  REGISTER_COMPANY_FAIL: 'REGISTER_COMPANY_FAIL',
  REGISTER_COMPANY_SUCCESS: 'REGISTER_COMPANY_SUCCESS',
  /*..GET JOBS ....*/
  GET_JOBS: 'GET_JOBS',
  GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
  GET_JOBS_FAIL: 'GET_JOBS_FAIL',
  /*..GET COMPANY POST ....*/
  GET_COMPAY_POST: 'GET_COMPAY_POST',
  GET_COMPAY_POST_SUCCESS: 'GET_COMPAY_POST_SUCCESS',
  GET_COMPAY_POST_FAIL: 'GET_COMPAY_POST_FAIL',
  /*..CREATE COMPANY POST ....*/
  CREATE_POST: 'GET_POST',
  CREATE_POST_SUCCESS: 'GET_POST_SUCCESS',
  CREATE_POST_FAIL: 'GET_POST_FAIL',
  /*..APPLY JOB....*/
  APPLY_JOB: 'APPLY_JOB',
  APPLY_JOB_SUCCESS: 'APPLY_JOB_SUCCESS',
  APPLY_JOB_FAIL: 'APPLY_JOB_FAIL',
  /* Forgot pass word */
  FORGOT_PASS: 'FORGOT_PASS',
  FORGOT_PASS_SUCCESS: 'FORGOT_PASS_SUCCESS',
  FORGOT_PASS_FAIL: 'FORGOT_PASS_SUCCESS',
  /* confirm code */
  CONFIRM_CODE: 'CONFIRM_CODE',
  CONFIRM_CODE_SUCCESS: 'CONFIRM_CODE_SUCCESS',
  CONFIRM_CODE_FAIL: 'CONFIRM_CODE_FAIL',
  /* Update password */
  UPDATE_PASS: 'UPDATE_PASS',
  UPDATE_PASS_SUCCESS: 'UPDATE_PASS_SUCCESS',
  UPDATE_PASS_FAIL: 'UPDATE_PASS_FAIL',
  /* CV*/
  CREATE_CV: 'CREATE_CV',
  CREATE_CV_SUCCESS: 'CREATE_CV_SUCCESS',
  CREATE_CV_FAIL: 'CREATE_CV_FAIL',
  /* GET CV */
  GET_CV: 'GET_CV',
  GET_CV_SUCCESS: 'GET_CV_SUCCESS',
  GET_CV_FAIL: 'GET_CV_FAIL',
  /* SEARCH_JOB */
  SEARCH_JOB: 'SEARCH_JOB',
  SEARCH_JOB_SUCCESS: 'SEARCH_JOB_SUCCESS',
  SEARCH_JOB_FAIL: 'SEARCH_JOB_FAIL',
};
