export const actionType = {
  /*..Login....*/
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  /*..Register ITer....*/
  REGISTER_ITER: 'REGISTER_ITER',
  REGISTER_ITER_FAIL: 'REGISTER_ITER_FAIL',
  REGISTER_ITER_SUCCESS: 'REGISTER_ITER_SUCCESS',
  /*..Register Company....*/
  REGISTER_COMPANY: 'REGISTER_COMPANY',
  REGISTER_COMPANY_FAIL: 'REGISTER_COMPANY_FAIL',
  REGISTER_COMPANY_SUCCESS: 'REGISTER_COMPANY_SUCCESS',
  /*..GET JOBS ....*/
  GET_JOBS: 'GET_JOBS',
  GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
  GET_JOBS_FAIL: 'GET_JOBS_FAIL',
};
