export const actionType = {
  /*..Login....*/
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  /*..Register ITer....*/
  REGISTER_ITER: 'REGISTER_ITER',
  REGISTER_ITER_FAIL: 'REGISTER_ITER_FAIL',
  REGISTER_ITER_SUCCESS: 'REGISTER_ITER_SUCCESS',
  /*..Register Company....*/
  REGISTER_COMPANY: 'REGISTER_COMPANY',
  REGISTER_COMPANY_FAIL: 'REGISTER_COMPANY_FAIL',
  REGISTER_COMPANY_SUCCESS: 'REGISTER_COMPANY_SUCCESS',
  /*..GET JOBS ....*/
  GET_JOBS: 'GET_JOBS',
  GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
  GET_JOBS_FAIL: 'GET_JOBS_FAIL',
  /*..GET COMPANY POST ....*/
  GET_COMPAY_POST: 'GET_COMPAY_POST',
  GET_COMPAY_POST_SUCCESS: 'GET_COMPAY_POST_SUCCESS',
  GET_COMPAY_POST_FAIL: 'GET_COMPAY_POST_FAIL',
  /*..CREATE COMPANY POST ....*/
  CREATE_POST: 'GET_POST',
  CREATE_POST_SUCCESS: 'GET_POST_SUCCESS',
  CREATE_POST_FAIL: 'GET_POST_FAIL',
  /*..APPLY JOB....*/
  APPLY_JOB: 'APPLY_JOB',
  APPLY_JOB_SUCCESS: 'APPLY_JOB_SUCCESS',
  APPLY_JOB_FAIL: 'APPLY_JOB_FAIL',
  /* Forgot pass word */
  FORGOT_PASS: 'FORGOT_PASS',
  FORGOT_PASS_SUCCESS: 'FORGOT_PASS_SUCCESS',
  FORGOT_PASS_FAIL: 'FORGOT_PASS_SUCCESS',
  /* confirm code */
  CONFIRM_CODE: 'CONFIRM_CODE',
  CONFIRM_CODE_SUCCESS: 'CONFIRM_CODE_SUCCESS',
  CONFIRM_CODE_FAIL: 'CONFIRM_CODE_FAIL',
  /* Update password */
  UPDATE_PASS: 'UPDATE_PASS',
  UPDATE_PASS_SUCCESS: 'UPDATE_PASS_SUCCESS',
  UPDATE_PASS_FAIL: 'UPDATE_PASS_FAIL',

  /* CV*/
  CREATE_CV: 'CREATE_CV',
  CREATE_CV_SUCCESS: 'CREATE_CV_SUCCESS',
  CREATE_CV_FAIL: 'CREATE_CV_FAIL',
  /* GET CV */
  GET_CV: 'GET_CV',
  GET_CV_SUCCESS: 'GET_CV_SUCCESS',
  GET_CV_FAIL: 'GET_CV_FAIL',

  /* SEARCH_JOB */
  SEARCH_JOB: 'SEARCH_JOB',
  SEARCH_JOB_SUCCESS: 'SEARCH_JOB_SUCCESS',
  SEARCH_JOB_FAIL: 'SEARCH_JOB_FAIL',
  /*..DELETE COMPANY POST ....*/
  DELETE_POST: 'GET_POST',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL: 'DELETE_POST_FAIL',
  /*..LIST ITER APPLY ....*/
  GET_LIST_APPLY: 'GET_LIST_APPLY',
  GET_LIST_APPLY_SUCCESS: 'GET_LIST_APPLY_SUCCESS',
  GET_LIST_APPLY_FAIL: 'GET_LIST_APPLY_FAIL',
  /* CHANGE PASSWORD */
  CHANGE_PASS_SUCCESS: 'CHANGE_PASS_SUCCESS',
  CHANGE_PASS_FAIL: 'CHANGE_PASS_FAIL',
  CHANGE_PASS: 'CHANGE_PASS',
  /* PROFILE */
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',

  /* UPDATE WAITING POST */
  UPDATE_WAITING_POST: 'UPDATE_WAITING_POST',
  UPDATE_WAITING_POST_SUCCESS: 'UPDATE_WAITING_POST_SUCCESS',
  UPDATE_WAITING_POST_FAIL: 'UPDATE_WAITING_POST_FAIL',

  /* UPDATE CV  */
  UPDATE_CV: 'UPDATE_CV',
  UPDATE_CV_SUCCESS: 'UPDATE_CV_SUCCESS',
  UPDATE_CV_FAIL: 'UPDATE_CV_FAIL',

  /* INFO COMPANIES  */
  COMPANIES: 'UPDATE_CV',
  COMPANIES_SUCCESS: 'COMPANIES_SUCCESS',
  COMPANIES_FAIL: 'COMPANIES_FAIL',

  /* JOB COMPANIES  */
  COMPANIES_JOB: 'COMPANIES_JOB',
  COMPANIES_JOB_SUCCESS: 'COMPANIES_JOB_SUCCESS',
  COMPANIES_JOB_FAIL: 'COMPANIES_JOB_FAIL',

  /* Feedback  */
  FEEDBACK: 'FEEDBACK',
  FEEDBACK_SUCCESS: 'FEEDBACK_SUCCESS',
  FEEDBACK_FAIL: 'FEEDBACK_FAIL',

  // Follow
  FOLLOW: 'FOLLOW',
  FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
  FOLLOW_FAIL: 'FOLLOW_FAIL',

  //get following
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_FOLLOWING_SUCCESS: 'GET_FOLLOWING_SUCCESS',
  GET_FOLLOWING_FAIL: 'GET_FOLLOWING_FAIL',
};
